---@class SearchItem
---@field name string
---@field category string
---@field texture number
---@field extraSearchText? string
---@field action? function
---@field macroText? string
---@field pickup? function
---@field tooltip? fun(limitedTooltip: LimitedTooltip) | string
