name: Update Generated Files

on: workflow_dispatch

jobs:
  update-secure-slash-commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update secure slash commands
        run: ./Scripts/update-secure-slash-commands.sh > Generated/SecureSlashCommands.lua

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: actions/update-secure-slash-commands
          title: Update secure slash commands
          commit-message: Update secure slash commands
          labels: chore
          delete-branch: true

  update-interface-options:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update interface options
        run: ./Scripts/update-interface-options.py > Generated/InterfaceOptions.lua

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: actions/update-interface-options
          title: Update interface options
          commit-message: Update interface options
          labels: chore
          delete-branch: true
