name: Test

on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install luarocks
        run: sudo apt-get install luarocks
      - name: Install luaunit
        run: sudo luarocks install luaunit
      - name: Run tests
        run: ./Scripts/test.sh
